<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ti" nsURI="ti" nsPrefix="ti">
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eAnnotations source="om=cov"/>
    <eAnnotations source="lm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__metamodels" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__supplementaries" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="__contains" upperBound="-1"
        eType="#//EClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__name" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__relationNames" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__potency" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__parentNodes" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__isAbstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__attributeNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="__supplementaryNodes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference" upperBound="-1"
        eType="#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BU" eSuperTypes="#//EClass">
    <eAnnotations source="type=IntegerValue@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pBU" upperBound="-1" eType="#//bedsUCI">
      <eAnnotations source="type=parameter@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PC" eSuperTypes="#//EClass">
    <eAnnotations source="type=IntegerValue@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pPC" upperBound="-1" eType="#//patients">
      <eAnnotations source="type=parameter@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UO" eSuperTypes="#//EClass">
    <eAnnotations source="type=Value@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vtUO" upperBound="-1" eType="#//DIV"
        containment="true">
      <eAnnotations source="type=valuetype@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="bedsUCI" eSuperTypes="#//EClass">
    <eAnnotations source="type=Parameter@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UCIoccupancy" eSuperTypes="#//EClass">
    <eAnnotations source="type=RiskIndicator"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasUO" upperBound="-1"
        eType="#//UO" containment="true">
      <eAnnotations source="type=has@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Impact" eSuperTypes="#//EClass">
    <eAnnotations source="type=Dimension@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tP" upperBound="-1" eType="#//patients"
        containment="true">
      <eAnnotations source="type=takes@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cUO" upperBound="-1" eType="#//UCIoccupancy"
        containment="true">
      <eAnnotations source="type=collects@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tB" upperBound="-1" eType="#//bedsUCI"
        containment="true">
      <eAnnotations source="type=takes@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="patients" eSuperTypes="#//EClass">
    <eAnnotations source="type=Parameter@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RiskEvaluation" eSuperTypes="#//EClass">
    <eAnnotations source="type=QualityModel@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cI" upperBound="-1" eType="#//Impact"
        containment="true">
      <eAnnotations source="type=contains@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DIV" eSuperTypes="#//EClass">
    <eAnnotations source="type=AggregatedIntegerValue@2"/>
    <eAnnotations source="suptypes"/>
    <eAnnotations source="potency=1-1-*"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vPC" upperBound="-1" eType="#//PC"
        containment="true">
      <eAnnotations source="type=values@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vBU" upperBound="-1" eType="#//BU"
        containment="true">
      <eAnnotations source="type=values@2"/>
      <eAnnotations source="potency=1-1-*"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
